### ISSUE TITLE
Problème d'ajout de tags/story

### ISSUE THREAD

**Issue by NathanBnm** [NathanBnm/ember-tds#1]
@jcheron je n'arrive pas à ajouter de tags / story, je ne sais pas ce que j'ai fais de mauvais.
Pouvez-vous regarder les fichiers concernés dans la branche TD4 svp ?

**Comment by jcheron** [comment]
Vous avez un problème de cohérence dans la logique applicative.
Les tags sont comme les labels des issues github.
Certains existent déjà, et quand on crée une Story, on peut lui ajouter un ou plusieurs tags, parmi ceux qui existent, ou en créer un nouveau, et lui ajouter.
