### ISSUE TITLE
Erreur avec le composant draggable-item

### ISSUE THREAD

**Issue by NathanBnm** [NathanBnm/ember-tds#4]
J'ai un problème avec le code suivant :

```js
  doubleClick() {
    this.sendAction("onDblClick", get(this, 'content'));
  },
  click() {
    this.sendAction("onClick", get(this, 'content'));
  }
```

Il n'aime pas le "this", voici ce que j'ai dans la console : 

```
C:\Users\Nathan\Projects\EmberJS\app\components\draggable-item.js
  19:5  error  Use closure actions  ember/closure-actions
  22:5  error  Use closure actions  ember/closure-actions

✖ 2 problems (2 errors, 0 warnings)
```

Je ne comprends pas ce qu'il faut modifier @jcheron.

**Comment by jcheron** [comment]
C'est juste une dépréciation du `this.sendAction`, que vous pouvez corriger dans le composant,
mais qui ne doit pas poser de pbs à l'exécution.
Voir https://github.com/emberjs/rfcs/blob/master/text/0335-deprecate-send-action.md

**Comment by NathanBnm** [comment]
Je ne comprends pas bien. J'ai fait comme ça mais ça ne change pas le problème : 

```js
  actions: {
    doubleClick() {
      this.sendAction("onDblClick", get(this, 'content'));
    },
    click() {
      this.sendAction("onClick", get(this, 'content'));
    }
  }
```

> 
> C'est juste une dépréciation du `this.sendAction`, que vous pouvez corriger dans le composant,
> mais qui ne doit pas poser de pbs à l'exécution.

Le déploiement sur Heroku ne va pas fonctionner si il y a des erreurs.

**Comment by jcheron** [comment]
Je n'ai aucun pb sur Heroku avec ce code...

**Comment by jcheron** [comment]
je regarde ça...

**Comment by NathanBnm** [comment]
@jcheron à priori c'est corrigé l'IDE n'avait pas actualisé
